---
- name: Create a VM from a template
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - name: CREATE_VMWARE_GUEST
    vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      folder: /datastore1/
      name: "rhel7.6_{{ vmware_guest_ip }}"
#      template: template_el7
#      datacenter: DC1
      state: poweredon
      wait_for_ip_address: yes
      cdrom:
        type: iso
        iso_path: "datastore1/iso/rhel/rhel-server-7.6-x86_64-dvd.iso"
#        iso_path: "[datastore1] iso/rhel/rhel-server-7.6-x86_64-dvd.iso"
      guest_id: rhel7_64Guest
        # This is hostname of particular ESXi server on which user wants VM to be deployed
#      esxi_hostname: "{{ esxi_hostname }}"
      disk:
      - size_gb: 50
        type: thick
        datastore: datastore1
      hardware:
        memory_mb: 2048
        num_cpus: 2
        scsi: paravirtual
      networks:
      - name: VM Network
        device_type: vmxnet3
      delegate_to: localhost
      register: deploy_vm
